### ISSUE TITLE
why not .net 4.5?

### ISSUE THREAD

**Issue by jenokizm** [tmarkovski/jwt-ec-signing#1]
Please, add support for the regular desktop.

**Comment by tmarkovski** [comment]
@jenokizm You should be able use it with .NET 4.5, it's supported under netstandard2.0

https://docs.microsoft.com/en-us/dotnet/standard/net-standard

Make sure to use to latests Visual Studio where tooling supports this. If not, you can recompile the library yourself, should be easy. Just replace Portable.BouncyCastle with the regular BouncyCastle package.

**Comment by tmarkovski** [comment]
Uploaded new package with multiple targets.

https://www.nuget.org/packages/Jwt.Ec/1.0.2
